providers = ["node"]

[variables]
NIXPACKS_NODE_VERSION = "20"
NEXT_TELEMETRY_DISABLED = "1"
DATA_DIR = "/app/data"

[phases.setup]
aptPkgs = ["python3", "make", "g++", "build-essential"]

[phases.install]
cmds = ["npm install --legacy-peer-deps"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "mkdir -p /app/data && npm run start"
